### PR TITLE
Assign company of contact to email

### PR DESCRIPTION
**Pull request by xolf**

### CODE REVIEW

**Comment by trippo** [comment]
Maybe it can be an config option

**Comment by xolf** [comment]
My thoughts came from the [BCC email address](https://knowledge.hubspot.com/settings/log-email-in-your-crm-with-the-bcc-or-forwarding-address) of HubSpot. They also assign the email to the contact and the companies contact.

We can also make a config for this. I think it should be enabled then by default and can be disabled.

**Comment by trippo** [comment]
Hubspot associate automatically email notification to the company (if the contact has a company) in my tests

**Comment by xolf** [comment]
I'm using this package for a lot of emails we're sending to our users. Attached you can see the emails tracked for a contact who freshly signed up. But for the company only the first email gets attached automatically and the other twos are missing. For me it seems like the email only gets attached to the company if it's freshly created. If the company already exists and an email gets tracked for a contact it's not going to be attached to the company.

---

**Contact emails**
Bildschirmfoto 2023-09-19 um 13 48 11

**Company emails**  
Bildschirmfoto 2023-09-19 um 13 48 07

**Comment by trippo** [comment]
You are right

**Comment by trippo** [comment]
@xolf I released a new version with API call refactor and API V4 use for associations

**Comment by xolf** [comment]
@trippo awesome!! Thank you for the refactoring and update. I just implemented a WIP, now everything is synced with HubSpot. ☺️

**Pull request merged**
